# Generated by Django 4.0 on 2022-12-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='slug',
            field=models.SlugField(default='no_slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, default='announcements_images/noImage.jpeg', null=True, upload_to='announcements_images/'),
        ),
    ]
